/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp InfoFrame.xml -v -c InfoFrameDBusAdaptor -a InfoFrameDBusAdaptor.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2016 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */
#include "InfoFrameDBusAdaptor.h"

/*
 * Implementation of adaptor class InfoFrameDBusAdaptor
 */

InfoFrameDBusAdaptor::InfoFrameDBusAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

InfoFrameDBusAdaptor::~InfoFrameDBusAdaptor()
{
    // destructor
}

void InfoFrameDBusAdaptor::updateVariableValue(int new_value)
{
    // handle method call org.DaliBox.GUIInterface.updateVariableValue
    QMetaObject::invokeMethod(parent(), "updateVariableValue", Q_ARG(int, new_value));
}

void InfoFrameDBusAdaptor::updateVariableValue2(int new_value)
{
    // handle method call org.DaliBox.GUIInterface.updateVariableValue2
    QMetaObject::invokeMethod(parent(), "updateVariableValue", Q_ARG(int, new_value));
}
